<?php


namespace Plafor\Database\Seeds;


use CodeIgniter\Database\Seeder;

class addOperationalCompetences2021Datas extends Seeder
{
    public function run()
    {
        $operational_competences = array(
            array('id' => '75','fk_competence_domain' => '21','name' => 'Clarifier et documenter les besoins  des parties prenantes dans le cadre d’un projet ICT','symbol' => 'A1','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '76','fk_competence_domain' => '21','name' => 'Définir un modèle de procédure pour un projet ICT','symbol' => 'A2','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '77','fk_competence_domain' => '21','name' => 'Rechercher des informations sur des solutions ICT et sur les innovations','symbol' => 'A3','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '78','fk_competence_domain' => '21','name' => 'Planifier les projets ICT et les tâches selon un modèle de procédure','symbol' => 'A4','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '79','fk_competence_domain' => '21','name' => 'Visualiser et présenter les variantes de solutions  ICT','symbol' => 'A5','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '80','fk_competence_domain' => '21','name' => 'Vérifier l’avancement des projets ICT et des tâches et en faire état selon le modèle de procédure','symbol' => 'A6','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '81','fk_competence_domain' => '21','name' => 'Remettre la solution ICT au client et clôturer le projet','symbol' => 'A7','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '82','fk_competence_domain' => '22','name' => 'Installer un PC monoposte','symbol' => 'B1','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '83','fk_competence_domain' => '22','name' => 'Réceptionner et traiter des demandes d’assistance informatique complexes','symbol' => 'B2','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '84','fk_competence_domain' => '22','name' => 'Conseiller les clients en matière de protection et de sécurité des données','symbol' => 'B3','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '85','fk_competence_domain' => '22','name' => 'Analyser, visualiser et documenter les processus métier des clients','symbol' => 'B4','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '86','fk_competence_domain' => '23','name' => 'Identifier et analyser les données et  développer des modèles de données','symbol' => 'C1','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '87','fk_competence_domain' => '23','name' => 'Mettre en œuvre des modèles de données dans un dispositif  de stockage de données numériques','symbol' => 'C2','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '88','fk_competence_domain' => '23','name' => 'Planifier, implé menter et documenter la sécurité et la protection des  données pour des solutions ICT','symbol' => 'C3','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '89','fk_competence_domain' => '23','name' => 'Traiter des données à partir de dispositifs de stockage de données numériques','symbol' => 'C4','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '90','fk_competence_domain' => '24','name' => 'Recueillir, stan dardiser et automati^ser les processus ICT','symbol' => 'D1','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '91','fk_competence_domain' => '24','name' => 'Définir le processus de livraison des  solutions ICT','symbol' => 'D2','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '92','fk_competence_domain' => '24','name' => 'Préparer la plateforme d’exécution des solutions ICT','symbol' => 'D3','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '93','fk_competence_domain' => '24','name' => 'Mettre en service les solutions ICT','symbol' => 'D4','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '94','fk_competence_domain' => '25','name' => 'Planifier et documenter les réseaux','symbol' => 'E1','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '95','fk_competence_domain' => '25','name' => 'Sélectionner et mettre en service les composants du réseau','symbol' => 'E2','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '96','fk_competence_domain' => '25','name' => 'Maintenir et développer les réseaux','symbol' => 'E3','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '97','fk_competence_domain' => '25','name' => 'Implémenter, documenter et vérifier la sécurité des réseaux','symbol' => 'E4','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '98','fk_competence_domain' => '25','name' => 'Analyser, opti miser et documenter la performance d’un réseau','symbol' => 'E5','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '99','fk_competence_domain' => '25','name' => 'Surveiller les réseaux','symbol' => 'E6','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '100','fk_competence_domain' => '26','name' => 'Planifier et documenter les systèmes  de serveurs et leurs services','symbol' => 'F1','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '101','fk_competence_domain' => '26','name' => 'Mettre en service les systèmes de serveurs','symbol' => 'F2','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '102','fk_competence_domain' => '26','name' => 'Mettre en service les services du serveur','symbol' => 'F3','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '103','fk_competence_domain' => '26','name' => 'Maintenir et administrer les systèmes de  serveurs et leurs services','symbol' => 'F4','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '104','fk_competence_domain' => '26','name' => 'Surveiller les systèmes de ser veurs et leurs ser^vices','symbol' => 'F5','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '105','fk_competence_domain' => '26','name' => 'Implémenter, documenter et vérifier la sécurité des systèmes de serveurs et  de leurs services','symbol' => 'F6','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '106','fk_competence_domain' => '26','name' => 'Planifier et mettre en œuvre la disponibilité des systèmes de serveurs et de leurs services','symbol' => 'F7','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '107','fk_competence_domain' => '26','name' => 'Etablir et mettre en œuvre des concepts de sauvegarde et d’archivage des données','symbol' => 'F8','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '108','fk_competence_domain' => '27','name' => 'Clarifier et documenter les besoins  des parties prenantes dans le cadre d’un projet ICT','symbol' => 'A1','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '109','fk_competence_domain' => '27','name' => 'Définir un modèle de procédure pour un projet ICT','symbol' => 'A2','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '110','fk_competence_domain' => '27','name' => 'Rechercher des informations sur des solutions ICT et sur les innovations','symbol' => 'A3','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '111','fk_competence_domain' => '27','name' => 'Planifier les projets ICT et les tâches selon un modèle de procédure','symbol' => 'A4','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '112','fk_competence_domain' => '27','name' => 'Visualiser et présenter les variantes de solutions  ICT','symbol' => 'A5','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '113','fk_competence_domain' => '27','name' => 'Vérifier l’avancement des projets ICT et des tâches et en faire état selon le modèle de procédure','symbol' => 'A6','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '114','fk_competence_domain' => '27','name' => 'Remettre la solution ICT au client et clôturer le projet','symbol' => 'A7','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '115','fk_competence_domain' => '28','name' => 'Installer un PC monoposte','symbol' => 'B1','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '116','fk_competence_domain' => '28','name' => 'Réceptionner et traiter des demandes d’assistance informatique complexes','symbol' => 'B2','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '117','fk_competence_domain' => '28','name' => 'Conseiller les clients en matière de protection et de sécurité des données','symbol' => 'B3','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '118','fk_competence_domain' => '28','name' => 'Analyser, visualiser et documenter les processus métier des clients','symbol' => 'B4','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '119','fk_competence_domain' => '29','name' => 'Identifier et analyser les données et  développer des modèles de données','symbol' => 'C1','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '120','fk_competence_domain' => '29','name' => 'Mettre en œuvre des modèles de données dans un dispositif  de stockage de données numériques','symbol' => 'C2','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '121','fk_competence_domain' => '29','name' => 'Planifier, implé menter et documenter la sécurité et la protection des  données pour des solutions ICT','symbol' => 'C3','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '122','fk_competence_domain' => '29','name' => 'Traiter des données à partir de dispositifs de stockage de données numériques','symbol' => 'C4','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '123','fk_competence_domain' => '30','name' => 'Analyser et documenter les besoins en  matière d’applications et d’interfaces','symbol' => 'G1','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '124','fk_competence_domain' => '30','name' => 'Vérifier la faisabilité technique des  prototypes d’interfaces utilisateur et les développer','symbol' => 'G2','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '125','fk_competence_domain' => '30','name' => 'Evaluer et documenter la sécurité  des applications et des interfaces','symbol' => 'G3','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '126','fk_competence_domain' => '30','name' => 'Elaborer des variantes de mise en  œuvre d’une application et développer la  solution sur le plan conceptuel','symbol' => 'G4','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '127','fk_competence_domain' => '30','name' => 'Implémenter les applications et les interfaces selon le concept en respectant les exigences  de sécurité','symbol' => 'G5','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '128','fk_competence_domain' => '30','name' => 'Vérifier la qualité et la sécurité des applications et des interfaces','symbol' => 'G6','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '129','fk_competence_domain' => '31','name' => 'Définir la plateforme appropriée  pour la livraison des applications','symbol' => 'H1','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '130','fk_competence_domain' => '31','name' => 'Définir le processus de livraison des  applications','symbol' => 'H2','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '131','fk_competence_domain' => '31','name' => 'Implémenter le processus de livraison des applications','symbol' => 'H3','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '132','fk_competence_domain' => '31','name' => 'Surveiller les applications et les interfaces  et résoudre les problèmes en cours de  fonctionnement','symbol' => 'H4','methodologic' => 'null','social' => 'null','personal' => 'null','archive' => NULL),
            array('id' => '133','fk_competence_domain' => '32','name' => 'Evaluer et mettre en service une place de travail utilisateur','symbol' => 'A1','methodologic' => 'Analyse des valeurs utiles, déroulement systématique, faire de checklist, technique commerciale, méthode durable de travail (économiquement, écologiquement, socialement)','social' => 'Orientation client, communication écrite et orale','personal' => 'Conscience de la responsabilité, fiabilité, autoréflexion critique','archive' => NULL),
            array('id' => '134','fk_competence_domain' => '32','name' => 'Installer et synchroniser sur le réseau interne des appareils mobiles des utilisateurs','symbol' => 'A2','methodologic' => 'Analyse des valeurs utiles, déroulement systématique, faire de checklist, technique commerciale, méthode durable de travail (économiquement, écologiquement, socialement)','social' => 'Orientation client, communication écrite et orale, comportement convivial avec le client','personal' => 'Conscience de la responsabilité, fiabilité, autoréflexion critique','archive' => NULL),
            array('id' => '135','fk_competence_domain' => '32','name' => 'Connecter et configurer des appareils périphériques','symbol' => 'A3','methodologic' => 'Analyse des valeurs utiles, déroulement systématique, faire de checklist, technique commerciale, méthode durable de travail (économiquement, écologiquement, socialement)','social' => 'Orientation client, communication écrite et orale, langage adapté au client','personal' => 'Conscience de la responsabilité, fiabilité, autoréflexion critique','archive' => NULL),
            array('id' => '136','fk_competence_domain' => '33','name' => 'Mettre en service des systèmes serveurs','symbol' => 'B1','methodologic' => 'Analyse des valeurs utiles, déroulement systématique, faire de checklist, technique commerciale, méthode durable de travail (économiquement, écologiquement, socialement)','social' => 'Orientation client, communication écrite et orale','personal' => 'Autoréflexion critique','archive' => NULL),
            array('id' => '137','fk_competence_domain' => '33','name' => 'Installer des réseaux et leurs topologies','symbol' => 'B2','methodologic' => 'Déroulement analytique, principe de Pareto, techniques de visualisation, diagrammes, techniques de décision','social' => 'Faire des entretiens professionnels en anglais','personal' => 'Méthode précise de travail, conscience de la responsabilité, capacités d’abstraction','archive' => NULL),
            array('id' => '138','fk_competence_domain' => '33','name' => 'Elaborer et mettre en œuvre des concepts de sécurité des données, de sécurité système et d’archivage','symbol' => 'B3','methodologic' => 'Actions préventives','social' => 'Conseil','personal' => 'Penser et travailler de manière disciplinée, comportement dans les situations de stress','archive' => NULL),
            array('id' => '139','fk_competence_domain' => '34','name' => 'Assurer la maintenance de réseaux et les développer','symbol' => 'C1','methodologic' => 'déroulement systématique, faire de checklist, technique commerciale, méthode durable de travail (économiquement, écologiquement, socialement)','social' => '','personal' => 'Précision, fiable, actions attentives','archive' => NULL),
            array('id' => '140','fk_competence_domain' => '34','name' => 'Assurer la maintenance et administrer des serveurs','symbol' => 'C2','methodologic' => 'Pensée systématique et préventive, considération de l’ensemble, remise en question systématique, travail durable (économiquement, écologiquement, socialement)','social' => 'Travail en groupe, entretien professionnel en anglais','personal' => 'Travail patient et autocritique, conscience de la qualité, autoréflexion, éthique, discrétion, discipline','archive' => NULL),
            array('id' => '141','fk_competence_domain' => '34','name' => 'Planifier, mettre en œuvre des services d’annuaires et des autorisations','symbol' => 'C3','methodologic' => 'Techniques d’interrogation','social' => 'Empathie','personal' => 'Comprendre et interpréter des documents anglais','archive' => NULL),
            array('id' => '142','fk_competence_domain' => '34','name' => 'Mettre en service et configurer des services de communication et de soutien des travaux de groupe (groupeware)','symbol' => 'C4','methodologic' => 'Techniques d’entretien, pensée systématique et préventive, considération de l’ensemble, remise en question systématique','social' => 'Travailler en groupe','personal' => 'Travail patient et auto-critique, sens de la qualité, autoreflexion','archive' => NULL),
            array('id' => '143','fk_competence_domain' => '35','name' => 'Instruire et aider les utilisateurs dans l’utilisation des moyens informatiques','symbol' => 'D1','methodologic' => 'Techniques d’interrogation, déroulement structuré, travailler selon checklist, établir des documents de première aide','social' => 'Capacité de communication, comportement avec autrui en situation de stress, comportement selon le niveau hiérarchique','personal' => 'Garder le calme, résistance au stress, maîtriser sa propre nervosité','archive' => NULL),
            array('id' => '144','fk_competence_domain' => '35','name' => 'Assurer des tâches de support par le biais du contact client et résoudre les problèmes sur place','symbol' => 'D2','methodologic' => 'Techniques d’interrogation, déroulement structuré, travailler selon checklist','social' => 'Capacité de communication, comportement avec autrui en situation de stress, comportement selon le niveau hiérarchique','personal' => 'Garder le calme, résistance au stress, maîtriser sa propre nervosité','archive' => NULL),
            array('id' => '145','fk_competence_domain' => '36','name' => 'Elaborer des concepts de tests, mettre en application divers déroulements de tests et tester systématiquement les applications ','symbol' => 'E1','methodologic' => '','social' => 'Capacité de critique mutuelle','personal' => 'Développer préventivement, estimer les conséquences','archive' => NULL),
            array('id' => '146','fk_competence_domain' => '36','name' => 'Développer et documenter des applications de manière conviviale en utilisant des modèles appropriés de déroulement','symbol' => 'E2','methodologic' => 'Utiliser efficacement l’environnement logiciels, travail systématique et structuré, capacités d’abstraction, compétences en modélisation, acquisition d’informations, développer efficacement, observer la charge du réseau','social' => 'Travail en groupe, capacités de communication, de critique, de compromis, orientation client, disponibilité, reprise de l’existant','personal' => 'Pensée économique, capacité de résistance, conscience de la qualité, capacité de saisie rapide','archive' => NULL),
            array('id' => '147','fk_competence_domain' => '36','name' => 'Développer et implémenter des interfaces utilisateurs pour des applications selon les besoins du client','symbol' => 'E3','methodologic' => 'Orientation client, concept centré sur l’utilisateur, application de techniques innovantes','social' => 'Travail en groupe, empathie','personal' => 'Capacité d’innovation, créativité','archive' => NULL),
            array('id' => '148','fk_competence_domain' => '36','name' => 'Mettre en œuvre des modèles de données dans une base de données','symbol' => 'E4','methodologic' => '','social' => '','personal' => 'Capacité d’abstraction','archive' => NULL),
            array('id' => '149','fk_competence_domain' => '36','name' => 'Accéder à des données à partir d’applications avec un langage approprié','symbol' => 'E5','methodologic' => '','social' => '','personal' => '','archive' => NULL),
            array('id' => '150','fk_competence_domain' => '37','name' => 'Préparer, structurer, exécuter et documenter des travaux et des mandats de manière systématique et efficace','symbol' => 'F1','methodologic' => 'Déroulement structuré, déroulement systématique selon checklist, documentation des travaux','social' => 'Travail en groupe, prêt à aider, intérêt global, tenir une conversation en langue étrangère, compréhension des rôles','personal' => 'Fiabilité, bon comportement, capacité élevée de charges, s’identifier à l’entreprise','archive' => NULL),
            array('id' => '151','fk_competence_domain' => '37','name' => 'Collaborer à des projets','symbol' => 'F2','methodologic' => 'Déroulement structuré, déroulement systématique selon checklist, documentation des travaux','social' => 'Travail en groupe, prêt à aider, intérêt global, tenir une conversation en langue étrangère, compréhension des rôles','personal' => 'Fiabilité, bon comportement, capacité élevée de charges, s’identifier à l’entreprise, réfléchir en commun dans le projet','archive' => NULL),
            array('id' => '152','fk_competence_domain' => '37','name' => 'Dans le cadre de projets, communiquer de manière ciblée et adaptée à l’interlocuteur','symbol' => 'F3','methodologic' => 'Méthodes de travail, pensée en réseau, techniques de présentation et de ventes','social' => 'Travail en groupe, communiquer conformément au niveau et aux utilisateurs, comportement respectueux et approprié avec toutes les personnes de contact à tous les niveaux, communication précise','personal' => 'Réflexion, prêt à apprendre, intérêt, capacité de critiques, capacité de résistance','archive' => NULL)
        );
        foreach ($operational_competences as $operational_competencee){
            $this->db->table('operational_competence')->insert($operational_competencee);
        }
    }

}